name: Warm tournament Admins

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions: {}

jobs:
  warm-admins:
    runs-on: ubuntu-latest
    steps:
      - name: Warm future tournaments Admin
        run: curl --fail --location --silent --show-error --max-time 20 "https://script.google.com/macros/s/AKfycbxMiumaPx3JI25L1sMWCdupGEptbYWPHJ_0_MK1clt2MXWogWqWfOXrPm2ksOBeiq4FKg/exec" > /dev/null
